# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BR3_8wzxqSO2gQ5X3CJPHbB9mKuGglbZ
"""

import argparse
parser = argparse.ArgumentParser(description='insert protein.') 
parser.add_argument('-full_protein_ID_foo', help='protein name', default='') 
args = parser.parse_args()